### PR TITLE
feat: create our team page

### LINKED ISSUE #7: Create Our Team page

### PR DESCRIPTION
**Pull request by sahanperera00**
fixes #7

localhost_5173_team (1)
localhost_5173_team

@uihalagedara @ThusharaX

### CODE REVIEW

**Comment by ThusharaX** [comment]
@sahanperera00 can you add some vertical margin in mobile view?

image

**Comment by sahanperera00** [comment]
> @sahanperera00 can you add some vertical margin in mobile view?
> 
> image

done

**Review by uihalagedara — APPROVED** [review]
LGTM

**Review by ThusharaX — APPROVED** [review]
LGTM

**Pull request merged**
