### PR TITLE
Vesak Zone Home Page Added

### PR DESCRIPTION
**Pull request by Randula98**

### CODE REVIEW

**Comment by Randula98** [comment]
Mobile View
image

image

**Comment by ThusharaX** [comment]
@Randula98 can you use the color that we used in figma design for the dark mode?
and **resolve conflicts**

image

**Comment by uihalagedara** [comment]
Please resolve the conflicts

**Review by uihalagedara — APPROVED** [review]

**Review by ThusharaX — APPROVED** [review]
LGTM

**Pull request merged**
