### PR TITLE
Hero sec

### PR DESCRIPTION
**Pull request by Navojith**
#3 

Screenshot 2023-05-02 225055

Screenshot 2023-05-02 225038

### CODE REVIEW

**Comment by Navojith** [comment]
pivot 😢 .

**Comment by ThusharaX** [comment]
> json approach wasn't successful. in local server it shows images as intended , but in vercel it does not. Therefore, pivot 😢 .

okay that's fine good job 🚀

**Review by ThusharaX — APPROVED** [review]
LGTM

**Review by Randula98 — APPROVED** [review]
LGTM

**Pull request merged**
